export const taskMap = [
    {
        id: 1,
        title: "Physics Engine Tuning",
        description: "Die Physikengine muss für die Otter angepasst werden",
        completed: false,
        createdAt: new Date("2023-01-01T00:00:00Z"),
        updatedAt: new Date("2023-01-10T00:00:00Z"),
        priority: "Medium",
        taskType: "ToDo",
        projectId: 1,
    },
    {
        id: 2,
        title: "3D Model Creation",
        description: "Für den MFD und deren Batterienhalterung müssen 3D Modelle erstellt werden",
        completed: false,
        createdAt: new Date("2023-01-01T00:00:00Z"),
        updatedAt: new Date("2023-01-10T00:00:00Z"),
        priority: "Medium",
        taskType: "Feature",
        projectId: 2,
    },
    {
        id: 3,
        title: "Test Task",
        description: "This is a test task",
        completed: false,
        createdAt: new Date("2023-01-01T00:00:00Z"),
        updatedAt: new Date("2023-01-10T00:00:00Z"),
        priority: "High",
        taskType: "Bug",
        projectId: 2,
    },
    {
        id: 4,
        title: "Implement New Feature",
        description: "Implement the new feature as discussed in the meeting",
        completed: false,
        createdAt: new Date("2023-01-01T00:00:00Z"),
        updatedAt: new Date("2023-01-10T00:00:00Z"),
        priority: "Low",
        taskType: "Feature",
        projectId: 3,
    },
    {
        id: 5,
        title: "Fix Critical Bug",
        description: "Fix the critical bug that is causing crashes",
        completed: false,
        createdAt: new Date("2023-01-01T00:00:00Z"),
        updatedAt: new Date("2023-01-10T00:00:00Z"),
        priority: "Critical",
        taskType: "Bug",
        projectId: 1,
    },
]